server:
  port: 9999

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.162.245:3306/aurora?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    #    url: jdbc:mysql://192.168.100.37:3306/aurora?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: cclucky
    password: 1234
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 114.132.162.245
    #    host: 192.168.100.37
    port: 6379
    #    password: 密码
    database: 1
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 100
        max-wait: 10000

  rabbitmq:
    host: 114.132.162.245
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

  elasticsearch:
    rest:
      uris: 114.132.162.245:9200

  mail:
    host: smtp.163.com
    username: 2226114701@qq.com
    password: 2222  # 瞎写
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


search:
  mode: elasticsearch

upload:
  mode: minio
  oss:
    url: https://cclucky-blog.oss-cn-guangzhou.aliyuncs.com/
    endpoint: oss-cn-guangzhou.aliyuncs.com
    accessKeyId: LTAI5tCAYu85LBSvXcyZxmMJ
    accessKeySecret: d2XfbSAs5VM42rtRfSIsf23vBL4oOM
    bucketName: cclucky-blog
  minio:
    url: https://minio.cclucky.top/cclucky-blog/
    endpoint: https://minio.cclucky.top
#    accessKey: 0jFNL7vP6JQAK6hm
#    secretKey: 2i2hu9EuTp5npOpjCWTDCptaIWNCSTX1
    accessKey: minio
    secretKey: minio@123
    bucketName: cclucky-blog


website:
  url: https://114.132.162.245/

qq:
  app-id: QQ APPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}

knife4j:
  production: false